"""
Example Align Plugin - Image Enhancement
Demonstrates how to create a plugin that hooks into the mockup generation workflow
"""

class ImageEnhancementPlugin:
    """
    Example plugin that enhances images before mockup generation.
    Shows how plugins can modify core workflows.
    """
    
    def __init__(self):
        self.name = "Image Enhancement Plugin"
        self.version = "1.0.0"
        self.config = {}
    
    async def initialize(self):
        """Called when plugin is loaded."""
        print(f"✓ {self.name} initialized")
    
    async def cleanup(self):
        """Called when plugin is unloaded."""
        print(f"✓ {self.name} cleaned up")
    
    async def configure(self, config):
        """Called when plugin configuration changes."""
        self.config = config
        print(f"✓ {self.name} configured: {config}")
    
    # Hook Methods (these are called by the plugin system)
    
    async def on_before_upload(self, file_content, filename):
        """
        Hook: Called before image upload processing
        Can modify the image before it's stored
        """
        print(f"🔧 Plugin processing upload: {filename}")
        
        # Example: Add watermark or resize image
        # In real implementation, you'd use PIL or similar
        
        return {
            "file_content": file_content,  # Return potentially modified content
            "filename": filename,
            "metadata": {
                "processed_by": self.name,
                "enhancement": "applied"
            }
        }
    
    async def on_before_mockup_generate(self, image_bytes, prompt, requirements):
        """
        Hook: Called before mockup generation
        Can modify the prompt or requirements
        """
        print(f"🔧 Plugin enhancing prompt: {prompt[:50]}...")
        
        # Example: Enhance the prompt with additional context
        enhanced_prompt = f"{prompt}\n\nAdditional context: Make the design modern and accessible."
        
        # Example: Add requirements
        enhanced_requirements = requirements.copy()
        enhanced_requirements["accessibility"] = True
        enhanced_requirements["modern_design"] = True
        
        return {
            "image_bytes": image_bytes,
            "prompt": enhanced_prompt,
            "requirements": enhanced_requirements
        }
    
    async def on_after_mockup_generate(self, mockup_html, mockup_id):
        """
        Hook: Called after mockup generation
        Can post-process the generated HTML
        """
        print(f"🔧 Plugin post-processing mockup: {mockup_id}")
        
        # Example: Add analytics tracking or custom CSS
        enhanced_html = mockup_html.replace(
            "</head>",
            """
            <style>
                /* Plugin-added styles */
                .plugin-enhanced {
                    border: 2px solid #10b981;
                    border-radius: 8px;
                }
            </style>
            <!-- Plugin: Image Enhancement Applied -->
            </head>
            """
        )
        
        return {
            "mockup_html": enhanced_html,
            "mockup_id": mockup_id,
            "plugin_metadata": {
                "enhanced_by": self.name,
                "enhancements": ["accessibility", "modern_design", "custom_styles"]
            }
        }
    
    async def on_custom_ai_provider(self, image_bytes, prompt):
        """
        Hook: Custom AI provider for mockup generation
        Can replace the default Gemini AI with custom logic
        """
        print(f"🤖 Plugin providing custom AI generation")
        
        # Example: Use a different AI service or custom logic
        # This is just a placeholder - in real implementation you'd call your AI service
        
        custom_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Custom AI Generated Mockup</title>
            <style>
                body {{ font-family: Arial, sans-serif; padding: 20px; }}
                .custom-ai {{ background: linear-gradient(45deg, #667eea 0%, #764ba2 100%); 
                             color: white; padding: 20px; border-radius: 10px; }}
            </style>
        </head>
        <body>
            <div class="custom-ai">
                <h1>Custom AI Mockup</h1>
                <p>Generated by {self.name}</p>
                <p>Prompt: {prompt}</p>
                <p>This demonstrates how plugins can provide custom AI generation.</p>
            </div>
        </body>
        </html>
        """
        
        return custom_html